// keep picture source for GUI //

import java.util.HashMap;
public class memberdata {
    public static String main(String key,Integer num){
        HashMap<String, String[]> member = new HashMap<String, String[]>();
        member.put("YIXING", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\yixing.jpg","EXO YIXING","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\yixingb.png"});
        member.put("XIUMIN", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\xiumin.jpg","EXO XIUMIN","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\xiuminb.png"});
        member.put("SUHO", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\suho.jpg","EXO SUHO","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\suhob.png"});
        member.put("SEHUN", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\sehun.jpg","EXO SEHUN","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\sehunb.png"});
        member.put("KAI", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\kai.jpg","EXO KAI","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\kaib.png"});
        member.put("D.O.", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\do.jpg","EXO D.O.","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\dob.png"});
        member.put("CHEN", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\chen.jpg","EXO CHEN","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\chenb.png"});
        member.put("CHANYEOL", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\chanyeol.jpg","EXO CHANYEOL","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\chanyeolb.png"});
        member.put("BAEKHYUN", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\baekhyun.jpg","EXO BAEKHYUN","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\baekhyunb.png"});
        member.put("TAEYONG", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\taeyong.jpg","NCT TAEYONG","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\taeyongb.png"});
        member.put("LUCAS", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\lucas.jpg","NCT LUCAS","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\lucasb.png"});
        member.put("JAEHYUN", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\jaehyun.jpg","NCT JAEHYUN","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\jaehyunb.png"});
        member.put("JAEMIN", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\jaemin.jpg","NCT JAEMIN","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\jaeminb.png"});
        member.put("JISUNG", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\jisung.jpg","NCT JISUNG","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\jisungb.png"});
        member.put("TEN", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\ten.jpg","NCT TEN","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\tenb.png"});
        member.put("MARK", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\mark.jpg","NCT MARK","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\markb.png"});
        member.put("YUTA", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\yuta.jpg","NCT YUTA","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\yutab.png"});
        member.put("JUNGWOO", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\jungwoo.jpg","NCT JUNGWOO","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\jungwoob.png"});
        member.put("CHENLE", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\chenle.jpg","NCT CHENLE","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\chenleb.png"});
        member.put("JENO", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\jeno.jpg","NCT JENO","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\jenob.png"});
        member.put("HAECHAN", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\haechan.jpg","NCT HAECHAN","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\haechanb.png"});
        member.put("WINWIN", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\winwin.jpg","NCT WINWIN","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\winwinb.png"});
        member.put("DOYOUNG", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\doyoung.jpg","NCT DOYOUNG","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\doyoungb.png"});
        member.put("TAEIL", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\taeil.jpg","NCT TAEIL","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\taeilb.png"});
        member.put("RENJUN", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\renjun.jpg","NCT RENJUN","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\renjunb.png"});
        member.put("JOHNNY", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\johnny.jpg","NCT JOHNNY","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\johnnyb.png"});
        member.put("KUN", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\kun.jpg","NCT KUN","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\kunb.png"});
        member.put("SIWON", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\siwon.jpg","SJ SIWON","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\siwonb.png"});
        member.put("DONGHAE", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\donghae.jpg","SJ DONGHAE","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\donghaeb.png"});
        member.put("HEECHUL", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\heechul.jpg","SJ HEECHUL","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\heechulb.png"});
        member.put("LEETEUK", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\leeteuk.jpg","SJ LEETEUK","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\leeteukb.png"});
        member.put("EUNHYUK", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\eunhyuk.jpg","SJ EUNHYUK","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\eunhyukb.png"});
        member.put("KYUHYUN", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\kyuhyun.jpg","SJ KYUHYUN","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\kyuhyunb.png"});
        member.put("YESUNG", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\yesung.jpg","SJ YESUNG","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\yesungb.png"});
        member.put("RYEOWOOK", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\ryeowook.jpg","SJ RYEOWOOK","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\ryeowookb.png"});
        member.put("SUNGMIN", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\sungmin.jpg","SJ SUNGMIN","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\sungminb.png"});
        member.put("SHINDONG", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\shindong.jpg","SJ SHINDONG","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\shindongb.png"});
        member.put("KANGIN", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\kangin.jpg","SJ KANGIN","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\kanginb.png"});
        member.put("IRENE", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\irene.jpg","RV IRENE","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\ireneb.png"});
        member.put("SEULGI", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\seulgi.jpg","RV SEULGI","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\seulgib.png"});
        member.put("WENDY", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\wendy.jpg","RV WENDY","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\wendyb.png"});
        member.put("JOY", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\joy.jpg","RV JOY","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\joyb.png"});
        member.put("YERI", new String[]{"C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member\\yeri.jpg","RV YERI","C:\\Users\\chanakanT\\Documents\\work\\Software\\Project\\Project\\member_border\\yerib.png"});
        return member.get(key)[num];
    }
}
